# ワークフローの名前
name: Publish to JSR

# ワークフローが実行されるタイミングを指定
on:
  push:
    tags:
      # 'v'で始まるタグ（例: v1.0.0, v1.2.3）がプッシュされたときに実行
      - "v*"

# 実行される一連のジョブを定義
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish --allow-slow-types --allow-dirty
